### ISSUE TITLE
Search Nginx, reverse proxying

### ISSUE THREAD

**Issue by cenkerozkan** [cenkerozkan/CoffeeGuide#16]

**Comment by SualpDnc** [comment]
Forward proxy, istemcinin (örneğin, bir kullanıcının bilgisayarı) dış dünyaya, özellikle internete erişiminde bir aracı olarak görev yapar. İstemci, internete doğrudan erişmek yerine forward proxy sunucusunu kullanır.Reverse proxy, bir veya daha fazla abckende gelen istekleri yönetir ve yönlendirir. İstemciler, doğrudan backende erişmek yerine reverse proxy sunucusuna istek gönderirler.

**Comment by SualpDnc** [comment]
Nginx, popüler bir web sunucusu ve ters proxy (reverse proxy) sunucusudur. İlk olarak web sunucusu olarak bilinse de, güçlü bir ters proxy olarak da yaygın şekilde kullanılır.

**Comment by cenkerozkan** [comment]
@SualpDnc Ellerine sağlık kapatıyorum bu taskı
